# Generated by Django 5.2.17 on 2026-09-09 12:27

import apps.orders.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='yesim', max_length=20)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('iccid', models.CharField(blank=True, db_index=True, max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Esim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('provider', models.CharField(default='yesim', max_length=20)),
                ('iccid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('provider_esim_id', models.CharField(blank=True, max_length=32)),
                ('provider_user_id', models.CharField(blank=True, max_length=32)),
                ('lpa_code', models.CharField(blank=True, max_length=255)),
                ('ios_tap_link', models.URLField(blank=True, max_length=500)),
                ('esim_passport_url', models.URLField(blank=True, max_length=500)),
                ('apn', models.CharField(blank=True, max_length=32)),
                ('imsi', models.CharField(blank=True, max_length=32)),
                ('msisdn', models.CharField(blank=True, max_length=32)),
                ('label', models.CharField(blank=True, help_text='Customer-visible nickname', max_length=80)),
                ('status_qr', models.CharField(choices=[('Released', 'Ready to install'), ('Installed', 'Installed'), ('Enabled', 'Active'), ('Disabled', 'Disabled'), ('Deleted', 'Removed from device')], default='Released', max_length=16)),
                ('active_plan_provider_id', models.CharField(blank=True, max_length=64)),
                ('plan_title', models.CharField(blank=True, max_length=180)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('plan_activated_at', models.DateTimeField(blank=True, null=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('data_package_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_used_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_left_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('network_info', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'esims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(db_index=True, default=apps.orders.models._ref, max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('kind', models.CharField(choices=[('new', 'New eSIM'), ('topup', 'Top-up')], default='new', max_length=10)),
                ('plan_title', models.CharField(max_length=180)),
                ('plan_provider_id', models.CharField(max_length=64)),
                ('plan_days', models.PositiveIntegerField(default=0)),
                ('plan_data_label', models.CharField(blank=True, max_length=32)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cost_currency', models.CharField(default='EUR', max_length=3)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid — provisioning'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('fulfillment_error', models.TextField(blank=True)),
                ('fulfillment_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.plan')),
                ('target_esim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topups', to='orders.esim')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='esim',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esims', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
    ]
