# Generated by Django 5.2.17 on 2026-09-12 07:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_seed_launch_coupons'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Guest order (audit)',
                'verbose_name_plural': 'Guest orders (audit)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='accept_language',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Frozen copy: the coupon row may be edited later', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='referrer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
