# Generated by Django 5.2.17 on 2026-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='analytics_sent',
            field=models.BooleanField(default=False),
        ),
    ]
