# Generated by Django 5.2.17 on 2026-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_analytics_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='withdrawal_waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
