# Generated by Django 5.2.17 on 2026-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_withdrawal_waived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_with_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(db_index=True, default='web', max_length=12),
        ),
    ]
