# Generated by Django 5.2.17 on 2026-09-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_paid_with_balance_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='support_id',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
