# Generated by Django 5.2.17 on 2026-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_gift_email_order_gift_message_order_gift_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
