# Generated by Django 5.2.17 on 2026-09-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_id', models.CharField(db_index=True, max_length=24, unique=True)),
                ('platform', models.CharField(default='android', max_length=12)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app install',
                'verbose_name_plural': 'app installs',
                'ordering': ('-last_seen',),
            },
        ),
    ]
