# Generated by Django 5.2.17 on 2026-09-14 09:38

from django.db import migrations, models




def grandfather_existing(apps, schema_editor):
    """Everyone who already has an account predates the rule.

    Enforcing verification from today would lock out every existing customer,
    including ones with live eSIMs, over a link they were never sent. The rule
    applies to registrations from here on.
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(email_verified=False).update(email_verified=True)


def unverify(apps, schema_editor):
    """Nothing to undo: unverifying accounts on a rollback would lock people out
    all over again, which is worse than an imprecise reverse migration."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appinstall'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(grandfather_existing, unverify),
    ]
