# Generated by Django 5.2.17 on 2026-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstall',
            name='integrity_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appinstall',
            name='integrity_verdict',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
