# Generated by Django 5.2.17 on 2026-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appinstall_integrity_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstall',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
