# Generated by Django 5.2.17 on 2026-09-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appinstall_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
