# Generated by Django 5.2.17 on 2026-09-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstall',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appinstall',
            name='integrity_verdict',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appinstall',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
