# Generated by Django 5.2.17 on 2026-10-06 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appinstall_app_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('signup', 'Sign-up'), ('login', 'Sign-in')], default='login', max_length=10)),
                ('method', models.CharField(choices=[('email', 'Email + password'), ('google', 'Google'), ('verify', 'Email confirmation link')], default='email', max_length=10)),
                ('surface', models.CharField(default='web', max_length=8)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sign-in / sign-up',
                'verbose_name_plural': 'sign-ins & sign-ups',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_lo_user_id_ebe614_idx'), models.Index(fields=['ip', '-created_at'], name='accounts_lo_ip_32a1e0_idx')],
            },
        ),
    ]
