# Generated by Django 5.2.17 on 2026-09-13 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('document', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=64)),
                ('surface', models.CharField(default='web', max_length=16)),
                ('context', models.CharField(choices=[('signup', 'Sign-up'), ('checkout', 'Checkout'), ('subscribe', 'Subscription start'), ('app', 'Mobile app'), ('reaccept', 'Re-accepted after a change')], default='checkout', max_length=16)),
                ('order_ref', models.CharField(blank=True, max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'document'], name='legal_legal_email_6ef5a7_idx'), models.Index(fields=['document', 'version'], name='legal_legal_documen_475bbb_idx')],
            },
        ),
    ]
