# Generated by Django 5.2.17 on 2026-09-14 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Shown in the list and used as the push title. Keep it short.', max_length=90, verbose_name='title')),
                ('body', models.TextField(max_length=1200, verbose_name='body')),
                ('kind', models.CharField(choices=[('promo', 'Offer'), ('news', 'News'), ('system', 'Service message')], db_index=True, default='promo', max_length=10)),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('has_esim', 'Customers with an eSIM'), ('no_purchase', 'Signed up, never bought'), ('has_balance', 'Customers holding balance'), ('no_balance', 'Customers with no balance')], default='all', max_length=16)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.CharField(blank=True, help_text='Absolute URL, or a path like /esim/japan/', max_length=300)),
                ('coupon_code', models.CharField(blank=True, help_text='Shown as a copyable code in the message.', max_length=40)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this it disappears from every inbox.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inbox message',
                'verbose_name_plural': 'inbox messages',
                'ordering': ('-publish_at',),
            },
        ),
        migrations.CreateModel(
            name='InboxRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='inbox.inboxmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inbox read',
                'verbose_name_plural': 'inbox reads',
                'constraints': [models.UniqueConstraint(fields=('user', 'message'), name='uniq_inbox_read')],
            },
        ),
    ]
