# Generated by Django 5.2.17 on 2026-09-12 07:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_plan_compare_at_usd'),
        ('orders', '0002_guestorder_order_accept_language_order_coupon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Payment failed'), ('canceled', 'Cancelled'), ('incomplete', 'Awaiting first payment'), ('paused', 'Paused')], db_index=True, default='incomplete', max_length=12, verbose_name='status')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per cycle (USD)')),
                ('interval_days', models.PositiveIntegerField(default=30, help_text='Mirrors the plan duration: 7, 15 or 30 days.', verbose_name='billing interval (days)')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='renews on')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='cancels at period end')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('renewals_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('esim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='orders.esim', verbose_name='eSIM')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalog.plan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='amount (USD)')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='paid', max_length=10, verbose_name='status')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cycles', to='orders.order', verbose_name='order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='subscriptions.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'subscription cycle',
                'verbose_name_plural': 'subscription cycles',
                'db_table': 'subscription_cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_302dc0_idx'),
        ),
    ]
