# Generated by Django 5.2.17 on 2026-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='funding',
            field=models.CharField(choices=[('card', 'Card (Stripe Billing)'), ('balance', 'Balance')], db_index=True, default='card', max_length=8, verbose_name='funded by'),
        ),
    ]
