# Generated by Django 5.2.17 on 2026-09-09 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe (card)'), ('nowpayments', 'NOWPayments (crypto)'), ('manual', 'Manual')], max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('provider_session_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='What actually arrived (crypto can underpay)', max_digits=10, null=True)),
                ('pay_currency', models.CharField(blank=True, max_length=20)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for funds'), ('confirming', 'Confirming'), ('paid', 'Paid'), ('partially_paid', 'Partially paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('settled', models.BooleanField(default=False, help_text='Order was released for fulfilment')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
