# Generated by Django 5.2.17 on 2026-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteConfig',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('maintenance', models.BooleanField(default=False, help_text='Blocks the app with the message below. For an outage bad enough that letting people try to buy would only take their money into a broken system.', verbose_name='maintenance mode')),
                ('maintenance_message', models.CharField(blank=True, default='We are fixing a problem and will be back shortly. Nothing you have bought is affected.', max_length=300, verbose_name='maintenance message')),
                ('min_supported_version', models.CharField(default='1.0.0', help_text='Installs older than this are sent to the store instead of being allowed to continue. Raise it only for a release that fixes something the old one gets wrong with money or data.', max_length=12, verbose_name='minimum app version')),
                ('notice_message', models.CharField(blank=True, help_text='Shown as a banner at the top of the app. Empty means no banner.', max_length=300, verbose_name='notice')),
                ('notice_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Serious problem')], default='info', max_length=10, verbose_name='notice level')),
                ('notice_url', models.URLField(blank=True, verbose_name='notice link')),
                ('notice_cta', models.CharField(blank=True, max_length=40, verbose_name='notice button')),
                ('card_payments', models.BooleanField(default=True, help_text='Off sends buyers to balance instead. The switch to reach for when Stripe, the payment sheet or 3-D Secure is misbehaving.', verbose_name='card payments in the app')),
                ('balance_payments', models.BooleanField(default=True, verbose_name='paying from balance')),
                ('balance_topups', models.BooleanField(default=True, verbose_name='adding balance')),
                ('guest_checkout', models.BooleanField(default=True, verbose_name='buying without an account')),
                ('gifting', models.BooleanField(default=True, verbose_name='gifting an eSIM')),
                ('referrals', models.BooleanField(default=True, verbose_name='referral codes')),
                ('coupons', models.BooleanField(default=True, verbose_name='discount codes')),
                ('subscriptions', models.BooleanField(default=True, verbose_name='subscriptions')),
                ('assistant', models.BooleanField(default=True, verbose_name='the chat assistant')),
                ('inbox', models.BooleanField(default=True, verbose_name='the inbox')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'app remote config',
                'verbose_name_plural': 'app remote config',
            },
        ),
    ]
