# Generated by Django 5.2.17 on 2026-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteconfig',
            name='guest_checkout',
            field=models.BooleanField(default=True, help_text='Closes guest checkout during an incident. It cannot open it: the setting GUEST_CHECKOUT decides whether it is offered at all, and that is off.', verbose_name='buying without an account'),
        ),
    ]
