# Generated by Django 5.2.17 on 2026-09-12 07:22

import apps.support.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=12, verbose_name='status')),
                ('intent_flags', models.CharField(blank=True, default='', max_length=120, verbose_name='intent flags')),
                ('owner_joined', models.BooleanField(default=False, verbose_name='operator joined')),
                ('user_unread', models.PositiveSmallIntegerField(default=0, verbose_name='unread for customer')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user agent')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='escalated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='last activity')),
            ],
            options={
                'verbose_name': 'assistant conversation',
                'verbose_name_plural': 'assistant conversations',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Customer'), ('assistant', 'Assistant'), ('owner', 'Support team')], max_length=10, verbose_name='written by')),
                ('content', models.TextField(verbose_name='message')),
                ('intent', models.CharField(blank=True, default='', max_length=60, verbose_name='intent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent')),
            ],
            options={
                'verbose_name': 'assistant message',
                'verbose_name_plural': 'assistant messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Customer'), ('staff', 'Support team')], default='user', max_length=8, verbose_name='written by')),
                ('body', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent')),
            ],
            options={
                'verbose_name': 'ticket message',
                'verbose_name_plural': 'ticket messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='ticket',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-updated_at',), 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='body',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('install', 'Installation and activation'), ('connection', 'No data or connection problem'), ('billing', 'Payments and billing'), ('refund', 'Refund request'), ('account', 'Account'), ('other', 'Something else')], default='other', max_length=16, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='opened'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='iccid',
            field=models.CharField(blank=True, max_length=32, verbose_name='ICCID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order_ref',
            field=models.CharField(blank=True, max_length=12, verbose_name='order reference'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ref',
            field=models.CharField(db_index=True, default=apps.support.models._ticket_ref, max_length=10, unique=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=160, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', '-updated_at'], name='support_tic_user_id_f0e394_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['email', '-updated_at'], name='support_tic_email_5f3307_idx'),
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.assistantconversation', verbose_name='conversation'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='ticket'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', '-updated_at'], name='support_ass_user_id_3a6456_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='support_ass_convers_26e8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
    ]
