# Generated by Django 5.2.17 on 2026-09-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_assistantconversation_assistantmessage_ticketmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantconversation',
            name='timeout_notified',
            field=models.BooleanField(default=False, verbose_name='waiting notice sent'),
        ),
    ]
