# Generated by Django 5.2.17 on 2026-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_assistantconversation_timeout_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAssistantMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('user_email', models.CharField(blank=True, db_index=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('intent', models.CharField(blank=True, default='', max_length=60)),
                ('message_created_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'assistant_message_archive',
                'ordering': ['conversation_id', 'message_created_at', 'archived_at'],
                'indexes': [models.Index(fields=['user_email', 'archived_at'], name='assistant_m_user_em_3ddf2a_idx')],
            },
        ),
    ]
