# Generated by Django 5.2.17 on 2026-09-13 21:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_paid_with_balance_order_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(db_index=True, max_length=20, unique=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('credited_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('credited', 'Credited'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('source', models.CharField(default='web', max_length=12)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'balance top-up',
                'verbose_name_plural': 'balance top-ups',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='balance')),
                ('topped_up_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('spent_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('topup', 'Balance added'), ('bonus', 'Bonus credit'), ('spend', 'Purchase'), ('refund', 'Refund to balance'), ('adjust', 'Manual adjustment')], db_index=True, max_length=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('balance_topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.balancetopup')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'ordering': ('-created_at',),
            },
        ),
    ]
