# Generated by Django 5.2.17 on 2026-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_referralpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetopup',
            name='received_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
