# Generated by Django 5.2.17 on 2026-09-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('flag_url', models.URLField(blank=True)),
                ('operators', models.TextField(blank=True, help_text='Comma-separated operator names from the provider')),
                ('continent', models.CharField(blank=True, db_index=True, max_length=32)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('min_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('plan_count', models.PositiveIntegerField(default=0)),
                ('has_unlimited', models.BooleanField(default=False)),
                ('intro', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=140)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(default='PHONE', max_length=20)),
                ('brand', models.CharField(db_index=True, max_length=60)),
                ('model', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ['brand', 'model'],
                'unique_together': {('brand', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Normalised provider label', max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🌍', max_length=8)),
                ('country_names', models.TextField(blank=True, help_text='Comma-separated, as reported by provider')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('min_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('plan_count', models.PositiveIntegerField(default=0)),
                ('has_unlimited', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=140)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='regions', to='catalog.country')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='yesim', max_length=20)),
                ('provider_plan_id', models.CharField(max_length=64, unique=True)),
                ('provider_old_id', models.CharField(blank=True, max_length=32)),
                ('provider_name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('country', 'Country'), ('region', 'Region')], db_index=True, max_length=10)),
                ('data_gb', models.DecimalField(blank=True, decimal_places=2, help_text='NULL = unlimited', max_digits=7, null=True)),
                ('is_unlimited', models.BooleanField(db_index=True, default=False)),
                ('days', models.PositiveIntegerField()),
                ('operators', models.TextField(blank=True)),
                ('apn', models.CharField(blank=True, max_length=32)),
                ('countries_iso2', models.TextField(blank=True, help_text='Comma-separated ISO2 list covered')),
                ('cost_amount', models.DecimalField(decimal_places=2, help_text='Wholesale price', max_digits=10)),
                ('cost_currency', models.CharField(default='EUR', max_length=3)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Computed retail price', max_digits=10)),
                ('price_override_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Manual retail price; wins over the formula', max_digits=10, null=True)),
                ('compare_at_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Typical competitor price for the strike-through', max_digits=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider_active', models.BooleanField(db_index=True, default=True, help_text='False when the plan disappeared from the provider feed')),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, help_text='e.g. Best value / Most popular', max_length=24)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.region')),
            ],
            options={
                'ordering': ['is_unlimited', 'days', 'data_gb'],
                'indexes': [models.Index(fields=['kind', 'is_active', 'provider_active'], name='catalog_pla_kind_fb9b1a_idx')],
            },
        ),
    ]
