# Generated by Django 5.2.17 on 2026-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='compare_at_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated typical price on competing eSIM apps. Shown as an explicit comparison ('the big apps typically charge ~$X'), never as a strike-through of our own price — that would imply a former price we never charged.", max_digits=10, null=True),
        ),
    ]
