# Generated by Django 5.2.17 on 2026-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_plan_compare_at_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='compare_at_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='List price: the same wholesale data at a normal retail margin (cost x PRICING_COMPARE_MULTIPLIER). Shown struck through as the going market rate, which is what the discount percentage is calculated against.', max_digits=10, null=True),
        ),
    ]
